api_platform:
    title: Hello API Platform
    version: 1.0.0
    # Good defaults for REST APIs
    defaults:
        stateless: true
        cache_headers:
            vary: ['Content-Type', 'Authorization', 'Origin']
        extra_properties:
            standard_put: true
        #pagination_items_per_page: 5
    formats:
        jsonld: [application/ld+json]
        json: [application/json]
        html: [text/html]
        jsonhal: [application/hal+json]
    swagger:
        api_keys:
            access_token:
                name: Authorization
                type: header
    keep_legacy_inflector: false
#    enable_docs: false
#    enable_entrypoint: false
#    enable_swagger: false
#    enable_swagger_ui: false